[workspace]
resolver = "2"
members = ["azure_core_amqp", "rust_wrapper"]

[workspace.package]
authors = ["Microsoft"]
edition = "2021"
license = "MIT"
repository = "https://github.com/azure/azure-sdk-for-rust"
rust-version = "1.76"


[workspace.dependencies.azure_core_amqp]
path = "azure_core_amqp"


[workspace.dependencies]
azure_core = { version = "0.18" }
azure_identity = "0.18"
async-lock = "3.0"
async-process = "2.0"
async-std = { version = "1.12", features = ["attributes"] }
async-trait = "0.1"
base64 = "0.22"
bytes = "1.0"
cbindgen = "0.26.0"
clap = { version = "4.4.16", features = ["derive"] }
dyn-clone = "1.0"
fe2o3-amqp = { version = "0.12", features = ["native-tls", "tracing", "uuid"] }
fe2o3-amqp-ext = { version = "0.12", features = [] }
fe2o3-amqp-management = { version = "0.12" }
fe2o3-amqp-cbs = { version = "0.12" }
fe2o3-amqp-types = { version = "0.12" }
futures = "0.3"
getrandom = { version = "0.2", features = ["js"] }
hmac = { version = "0.12" }
http-types = { version = "2.12", default-features = false }
oauth2 = { version = "4.0.0", default-features = false }
once_cell = "1.18"
openssl = { version = "0.10.46" }
paste = "1.0"
pin-project = "1.0"
quick-xml = { version = "0.31", features = ["serialize", "serde-types"] }
rand = "0.8"
reqwest = { version = "0.12", features = [
  "json",
  "stream",
], default-features = false }
rustc_version = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_amqp = { version = "0.12.2", features = ["uuid"] }
serde_bytes = { version = "0.11" }
serde_json = "1.0"
serde_test = "1"
serial_test = "3.0"
sha2 = { version = "0.10" }
thiserror = "1.0"
time = { version = "0.3.10", features = [
  "serde-well-known",
  "macros",
  "wasm-bindgen",
] }
tokio = { version = "1.0", default-features = false, features = [
  "rt-multi-thread",
  "macros",
  "time",
] }
tracing = "0.1.40"
tracing-subscriber = "0.3"
tz-rs = { version = "0.6" }
url = "2.2"
uuid = { version = "1.0", features = ["v4"] }

[workspace.lints]
