# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/identity

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/identity

parameters:
- name: PackageVersions
  displayName: PackageVersions (regex of package versions to run)
  type: string
  default: '1|source'
- name: Tests
  displayName: Tests (regex of tests to run)
  type: string
  default: '.*'
- name: Arguments
  displayName: Arguments (regex of arguments to run)
  type: string
  default: '.*'
- name: Iterations
  displayName: Iterations (times to run each test)
  type: number
  default: '5'
- name: Profile
  type: boolean
  default: false
- name: AdditionalArguments
  displayName: AdditionalArguments (passed to PerfAutomation)
  type: string 
  default: ' '

extends:
  template: /eng/pipelines/templates/jobs/perf.yml
  parameters:
    ServiceDirectory: identity/azure-identity
    PackageVersions: ${{ parameters.PackageVersions }}
    Tests: ${{ parameters.Tests }}
    Arguments: ${{ parameters.Arguments }}
    Iterations: ${{ parameters.Iterations }}
    AdditionalArguments: ${{ parameters.AdditionalArguments }}
    Profile: ${{ parameters.Profile }}
    EnvVars:
      # This is set in the InstallLanguageSteps
      VCPKG_BINARY_SOURCES_SECRET: $(VCPKG_BINARY_SOURCES_SECRET)
