trigger: none

extends:
    template: /eng/pipelines/templates/stages/archetype-sdk-tests.yml
    parameters:
      PackageName: azure-identity-cpp
      ServiceDirectory: identity/azure-identity
      TimeoutInMinutes: 120
      SupportedClouds: 'Public,UsGov,China,Canary'
      CloudConfig:
        Public:
          SubscriptionConfigurations:
            - $(sub-config-azure-cloud-test-resources)
            - $(sub-config-identity-test-resources)
          ServiceConnection: azure-sdk-tests
      EnvVars:
        AZURE_CLIENT_ID: $(IDENTITY_CLIENT_ID)
        AZURE_CLIENT_SECRET: $(IDENTITY_CLIENT_SECRET)
        AZURE_TENANT_ID: $(IDENTITY_TENANT_ID)
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
