# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/identity

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/identity

stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: identity
      CtestRegex: azure-identity.
      LiveTestCtestRegex: azure-identity.
      LineCoverageTarget: 95
      BranchCoverageTarget: 57
      Artifacts:
        - Name: azure-identity
          Path: azure-identity
          VcpkgPortName: azure-identity-cpp
      ArtifactsSource:
        - Name: azure-identity
          Path: azure-identity
          VcpkgPortName: azure-identity-cpp
      TestEnv:
        # Tenant ID should use the uniqueID format for playback recordings
        - Name: AZURE_TENANT_ID
          Value: "33333333-3333-3333-3333-333333333333"
        - Name: AZURE_CLIENT_ID
          Value: "non-real-client"
        - Name: AZURE_CLIENT_SECRET
          Value: "non-real-secret"
      CMakeTestOptions:
        - Name: Default
          Value: ''
        - Name: Test
          Value: '-DBUILD_TESTING=ON'
        - Name: Samples
          Value: '-DBUILD_TESTING=ON -DBUILD_SAMPLES=ON'
        - Name: Performance
          Value: '-DBUILD_TESTING=ON -DBUILD_SAMPLES=ON -DBUILD_PERFORMANCE_TESTS=ON'
      CMakeSourceTestOptions:
        - Name: Source
          Value: '-DFETCH_SOURCE_DEPS=ON'
