// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) TypeSpec Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

#include "azure/keyvault/secrets/generated/models/generated_models.hpp"

using namespace Azure::Security::KeyVault::Secrets::Generated::Models;

DeletionRecoveryLevel const DeletionRecoveryLevel::Purgeable{"Purgeable"};
DeletionRecoveryLevel const DeletionRecoveryLevel::RecoverablePurgeable{"Recoverable+Purgeable"};
DeletionRecoveryLevel const DeletionRecoveryLevel::Recoverable{"Recoverable"};
DeletionRecoveryLevel const DeletionRecoveryLevel::RecoverableProtectedSubscription{
    "Recoverable+ProtectedSubscription"};
DeletionRecoveryLevel const DeletionRecoveryLevel::CustomizedRecoverablePurgeable{
    "CustomizedRecoverable+Purgeable"};
DeletionRecoveryLevel const DeletionRecoveryLevel::CustomizedRecoverable{"CustomizedRecoverable"};
DeletionRecoveryLevel const DeletionRecoveryLevel::CustomizedRecoverableProtectedSubscription{
    "CustomizedRecoverable+ProtectedSubscription"};
