# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/eventhubs

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/eventhubs
      - eng/common/testproxy

stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: eventhubs
      CtestRegex: "azure-messaging-eventhubs.*"
      LiveTestCtestRegex: "azure-messaging-eventhubs.*"
      LiveTestTimeoutInMinutes: 120
      LineCoverageTarget: 40
      BranchCoverageTarget: 20
      Artifacts:
        - Name: azure-messaging-eventhubs
          Path: azure-messaging-eventhubs
          VcpkgPortName: azure-messaging-eventhubs-cpp
      ArtifactsSource:
        - Name: azure-messaging-eventhubs
          Path: azure-messaging-eventhubs
          VcpkgPortName: azure-messaging-eventhubs-cpp
      TestEnv:
        - Name: AZURE_TENANT_ID
          Value: "33333333-3333-3333-3333-333333333333"
        - Name: AZURE_CLIENT_ID
          Value: "non-real-client"
        - Name: AZURE_CLIENT_SECRET
          Value: "non-real-secret"
        - Name: AZURE_SUBSCRIPTION_ID
          Value: "non-real-sub"
        - Name: CHECKPOINTSTORE_STORAGE_CONNECTION_STRING
          Value: "DefaultEndpointsProtocol=https;AccountName=notReal;AccountKey=3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333;EndpointSuffix=core.windows.net"

      CMakeTestOptions:
        - Name: Default
          Value: ''
        - Name: Test
          Value: '-DBUILD_TESTING=ON'
        - Name: Samples
          Value: '-DBUILD_TESTING=ON -DBUILD_SAMPLES=ON'
        - Name: Performance
          Value: '-DBUILD_TESTING=ON -DBUILD_SAMPLES=ON -DBUILD_PERFORMANCE_TESTS=ON'
      CMakeSourceTestOptions:
        - Name: Source
          Value: '-DFETCH_SOURCE_DEPS=OFF'
