// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) TypeSpec Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

#pragma once

#include "azure/security/keyvault/secrets/secrets_models.hpp"

#include <azure/core/internal/client_options.hpp>
#include <azure/core/nullable.hpp>

#include <cstdint>
#include <string>

namespace Azure { namespace Security { namespace KeyVault { namespace Secrets {
  /**
   * @brief GeneratedSecretClient options.
   *
   */
  struct GeneratedSecretClientOptions final : public Core::_internal::ClientOptions
  {
    ///
    std::string ApiVersion = "7.6-preview.1";
  };

  /**
   * @brief GetPropertiesOfSecrets operation options.
   *
   */
  struct GeneratedSecretClientGetPropertiesOfSecretsOptions final
  {
    ///
    std::string NextPageToken;

    /// Maximum number of results to return in a page. If not specified the service will return up
    /// to 25 results.
    Nullable<std::int32_t> Maxresults;
  };

  /**
   * @brief GetPropertiesOfSecretsVersions operation options.
   *
   */
  struct GeneratedSecretClientGetPropertiesOfSecretsVersionsOptions final
  {
    ///
    std::string NextPageToken;

    /// Maximum number of results to return in a page. If not specified the service will return up
    /// to 25 results.
    Nullable<std::int32_t> Maxresults;
  };

  /**
   * @brief GetDeletedSecrets operation options.
   *
   */
  struct GeneratedSecretClientGetDeletedSecretsOptions final
  {
    ///
    std::string NextPageToken;

    /// Maximum number of results to return in a page. If not specified the service will return up
    /// to 25 results.
    Nullable<std::int32_t> Maxresults;
  };
}}}} // namespace Azure::Security::KeyVault::Secrets
