// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) TypeSpec Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

#pragma once

#include "azure/security/keyvault/secrets/generated_secret_client_options.hpp"
#include "azure/security/keyvault/secrets/secrets_models.hpp"

#include <azure/core/datetime.hpp>
#include <azure/core/internal/extendable_enumeration.hpp>
#include <azure/core/nullable.hpp>
#include <azure/core/paged_response.hpp>

#include <cstdint>
#include <map>
#include <memory>
#include <string>
#include <utility>
#include <vector>

namespace Azure { namespace Security { namespace KeyVault { namespace Secrets {
  class GeneratedSecretClient;

  /**
   * @brief The secret list result.
   *
   */
  class GetPropertiesOfSecretsPagedResponse final
      : public Core::PagedResponse<GetPropertiesOfSecretsPagedResponse> {
    friend class GeneratedSecretClient;
    friend class Core::PagedResponse<GetPropertiesOfSecretsPagedResponse>;

  private:
    std::shared_ptr<GeneratedSecretClient> m_client;
    GeneratedSecretClientGetPropertiesOfSecretsOptions m_options;

    void OnNextPage(Core::Context const& context);

  public:
    /// A response message containing a list of secrets in the key vault along with a link to the
    /// next page of secrets.
    Nullable<std::vector<SecretItem>> Value;
  };

  /**
   * @brief The secret list result.
   *
   */
  class GetPropertiesOfSecretsVersionsPagedResponse final
      : public Core::PagedResponse<GetPropertiesOfSecretsVersionsPagedResponse> {
    friend class GeneratedSecretClient;
    friend class Core::PagedResponse<GetPropertiesOfSecretsVersionsPagedResponse>;

  private:
    std::shared_ptr<GeneratedSecretClient> m_client;
    std::string m_secretName;
    GeneratedSecretClientGetPropertiesOfSecretsVersionsOptions m_options;

    void OnNextPage(Core::Context const& context);

  public:
    /// A response message containing a list of secrets in the key vault along with a link to the
    /// next page of secrets.
    Nullable<std::vector<SecretItem>> Value;
  };

  /**
   * @brief The deleted secret list result
   *
   */
  class GetDeletedSecretsPagedResponse final
      : public Core::PagedResponse<GetDeletedSecretsPagedResponse> {
    friend class GeneratedSecretClient;
    friend class Core::PagedResponse<GetDeletedSecretsPagedResponse>;

  private:
    std::shared_ptr<GeneratedSecretClient> m_client;
    GeneratedSecretClientGetDeletedSecretsOptions m_options;

    void OnNextPage(Core::Context const& context);

  public:
    /// A response message containing a list of deleted secrets in the key vault along with a link
    /// to the next page of deleted secrets.
    Nullable<std::vector<DeletedSecretItem>> Value;
  };
}}}} // namespace Azure::Security::KeyVault::Secrets
