# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/template

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/template

stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: template
      CtestRegex: azure-template
      Artifacts:
        - Name: azure-template
          Path: azure-template
          VcpkgPortName: azure-template-cpp
      TestEnv:
      # NOTE: The CI pipeline uppercases all "Name" values in the TestEnv, so if you
      # add a mixed case name, be careful to ensure it is read using an upper case
      # name.
      - Name: AZURE_SERVICE_DIRECTORY
        Value: TEMPLATE
