# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/tables

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/tables
      - eng/common/testproxy

extends:
    template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: tables
      LineCoverageTarget: 77
      BranchCoverageTarget: 42
      Artifacts:
        - Name: azure-data-tables
          Path: azure-data-tables
          VcpkgPortName: azure-data-tables-cpp
      TestEnv:
        - Name: ACCOUNT_NAME
          Value: 'account-name'
      CMakeTestOptions:
        - Name: Default
          Value: ''
        - Name: Test
          Value: '-DBUILD_TESTING=ON'
