parameters:
  "service-dir":
    default: "sdk/keyvault"

emit:
  - "@azure-tools/typespec-autorest"

linter:
  extends:
    - "@azure-tools/typespec-azure-core/all"

options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/.."
    examples-directory: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
  "@azure-tools/typespec-cpp":
    flavor: azure
    package-dir: "azure-security-keyvault-secrets"
    namespace: "Azure::Security::KeyVault::Secrets"
    typeRename:
     - from: "SecretUpdateParameters"
       to: "UpdateSecretPropertiesOptions"
     - from: "SecretClientGetPropertiesOfSecretsVersionsOptions"
       to: "GetPropertiesOfSecretVersionsOptions"
     - from: "GetPropertiesOfSecretsPagedResponse"
       to: "SecretPropertiesPagedResponse"
    #- from: "GetPropertiesOfSecretsVersionsPagedResponse"
    #  to: "SecretPropertiesPagedResponse"
     - from: "DeleteSecretOperation"
       to: "DeletedSecret"
     - from: "GetDeletedSecretsPagedResponse"
       to: "DeletedSecretPagedResponse"
     - from: "PurgeDeletedSecretResult"
       to: "PurgedSecret"
     - from: "GetDeletedSecretsPagedResponse"
       to: "DeletedSecretPagedResponse"
     - from: "SecretClientGetDeletedSecretsOptions"
       to: "GetDeletedSecretsOptions"
     - from: "SecretClientGetPropertiesOfSecretsOptions"
       to: "GetPropertiesOfSecretsOptions"
     - from: "SecretClientGetPropertiesOfSecretsVersionsOptions"
       to: "GetPropertiesOfSecretVersionsOptions"
     #- from: "SecretUpdateParameters"
     #  to: "SecretProperties"

