# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/appconfiguration

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/appconfiguration

extends:
    template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: appconfiguration
      CtestRegex: '^azure-data-appconfiguration.*$'
      LineCoverageTarget: 0
      BranchCoverageTarget: 0
      Artifacts:
        - Name: azure-data-appconfiguration
          Path: azure-data-appconfiguration
          VcpkgPortName: azure-data-appconfiguration-cpp
