# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - eng/
      - CMakeLists.txt
      - sdk/core
      - sdk/storage

pr:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - eng/
      - CMakeLists.txt
      - sdk/core/
      - sdk/storage

stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: storage
      # TODO: Change to azure-storage once we have an strategy to run livetests or use test recordings
      CtestRegex: azure-core
      Artifacts:
        - Name: azure-storage-common
          Path: azure-storage-common
        - Name: azure-storage-blobs
          Path: azure-storage-blobs
        - Name: azure-storage-files-datalake
          Path: azure-storage-files-datalake
        - Name: azure-storage-files-shares
          Path: azure-storage-files-shares
