# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/storage

pr:
  branches:
    include:
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/storage
      - eng/common/testproxy

stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: storage
      # Not running tests on CI but only on LiveTest mode
      CtestRegex: azure-storage
      LineCoverageTarget: 85
      BranchCoverageTarget: 50
      LiveTestCtestRegex: azure-storage
      Clouds: Preview
      SupportedClouds: Preview
      Artifacts:
        - Name: azure-storage-common
          Path: azure-storage-common
          VcpkgPortName: azure-storage-common-cpp
        - Name: azure-storage-blobs
          Path: azure-storage-blobs
          VcpkgPortName: azure-storage-blobs-cpp
        - Name: azure-storage-files-datalake
          Path: azure-storage-files-datalake
          VcpkgPortName: azure-storage-files-datalake-cpp
        - Name: azure-storage-files-shares
          Path: azure-storage-files-shares
          VcpkgPortName: azure-storage-files-shares-cpp
        - Name: azure-storage-queues
          Path: azure-storage-queues
          VcpkgPortName: azure-storage-queues-cpp
      TestEnv:
        - Name: AAD_TENANT_ID
          Value: "72f988bf-86f1-41af-91ab-2d7cd011db47"
        - Name: AAD_CLIENT_ID
          Value: "non-real-client"
        - Name: AAD_CLIENT_SECRET
          Value: "non-real-secret"          
        - Name: STANDARD_STORAGE_CONNECTION_STRING
          Value: "DefaultEndpointsProtocol=https;AccountName=notReal;AccountKey=3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333;EndpointSuffix=core.windows.net"
        - Name: ADLS_GEN2_CONNECTION_STRING
          Value: "DefaultEndpointsProtocol=https;AccountName=notReal;AccountKey=3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333;EndpointSuffix=core.windows.net"
        - Name: PREMIUM_FILE_CONNECTION_STRING
          Value: "DefaultEndpointsProtocol=https;AccountName=notReal;AccountKey=3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333;EndpointSuffix=core.windows.net"
        # Tables related env vars
        - Name: STORAGE_TENANT_ID
          Value: "72f988bf-86f1-41af-91ab-2d7cd011db47"
        - Name: STORAGE_CLIENT_ID
          Value: "non-real-client"
        - Name: STORAGE_CLIENT_SECRET
          Value: "some-secret"
        - Name: STORAGE_SUBSCRIPTION_ID
          Value: "72f988bf-86f1-41af-91ab-2d7cd011db47"
        - Name: STORAGE_RESOURCE_GROUP
          Value: "rg-fake"
        - Name: TABLES_STORAGE_ACCOUNT_NAME
          Value: "account-name"
        - Name: LOGGING__LOGLEVEL__DEFAULT
          Value: "debug"
      CMakeTestOptions:
        - Name: Default
          Value: ''
        - Name: Test
          Value: '-DBUILD_TESTING=ON'
