parameters:
  "service-dir":
    default: "sdk/keyvault"

emit:
  - "@azure-tools/typespec-autorest"

linter:
  extends:
    - "@azure-tools/typespec-azure-core/all"

options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/.."
    examples-directory: "{project-root}/examples"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
  "@azure-tools/typespec-cpp":
    flavor: azure
    package-dir: "azure-security-keyvault-certificates"
    namespace: "Azure::Security::KeyVault::Certificates::_detail"
    headersOutputPath: "azure/keyvault/certificates"
    noPublicHeaders: true
