trigger: none

extends:
  template: /eng/common/pipelines/templates/steps/prepare-pipelines.yml
  parameters:
    Repository: $(Build.Repository.Name)
    Prefix: cpp
    CIConventionOptions: ''
    UPConventionOptions: '--variablegroup 58 --variablegroup 76 --variablegroup 56'
    TestsConventionOptions: ''
