trigger: none

extends:
  template: /eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  parameters:
    Repository: $(Build.Repository.Name)
    Prefix: cpp
    CIConventionOptions: ''
    UPConventionOptions: '--variablegroups 58 76 64 93 117'
    TestsConventionOptions: ''
