// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

#pragma once

#include <azure/core/context.hpp>
#include <azure/core/datetime.hpp>
#include <azure/core/internal/http/pipeline.hpp>
#include <azure/core/nullable.hpp>
#include <azure/core/response.hpp>
#include <azure/core/url.hpp>

#include <memory>
#include <string>

namespace Azure { namespace Security { namespace KeyVault { namespace Administration {
  struct Error final
  {
  };

  struct FullBackupOperation final
  {
    std::string Status;
    std::string StatusDetails;
    Administration::Error Error;
    DateTime StartTime;
    Nullable<DateTime> EndTime;
    std::string JobId;
    std::string AzureStorageBlobContainerUri;
  };

  struct SasTokenParameter final
  {
    std::string StorageResourceUri;
    Nullable<std::string> Token;
    Nullable<bool> UseManagedIdentity;
  };

  struct FullBackupOptions final
  {
    SasTokenParameter AzureStorageBlobContainerUri;
  };

  struct FullBackupStatusOptions final
  {
    std::string JobId;
  };

  struct RestoreOperation final
  {
    std::string Status;
    std::string StatusDetails;
    Administration::Error Error;
    std::string JobId;
    DateTime StartTime;
    Nullable<DateTime> EndTime;
  };

  struct RestoreOperationParameters final
  {
    SasTokenParameter SasTokenParameters;
    std::string FolderToRestore;
  };

  struct FullRestoreOperationOptions final
  {
    RestoreOperationParameters RestoreBlobDetails;
  };

  struct RestoreStatusOptions final
  {
    std::string JobId;
  };

  struct SelectiveKeyRestoreOperation final
  {
    std::string Status;
    std::string StatusDetails;
    Administration::Error Error;
    std::string JobId;
    DateTime StartTime;
    Nullable<DateTime> EndTime;
  };

  struct SelectiveKeyRestoreOperationParameters final
  {
    SasTokenParameter SasTokenParameters;
    std::string Folder;
  };

  struct SelectiveKeyRestoreOperationOptions final
  {
    std::string KeyName;
    SelectiveKeyRestoreOperationParameters RestoreBlobDetails;
  };

  class KeyVaultClient final {
  public:
    explicit KeyVaultClient(std::string const& vaultBaseUrl);

    Response<FullBackupOperation> FullBackup(
        FullBackupOptions const& options = {},
        Core::Context const& context = {});

    Response<FullBackupOperation> FullBackupStatus(
        FullBackupStatusOptions const& options = {},
        Core::Context const& context = {});

    Response<RestoreOperation> FullRestoreOperation(
        FullRestoreOperationOptions const& options = {},
        Core::Context const& context = {});

    Response<RestoreOperation> RestoreStatus(
        RestoreStatusOptions const& options = {},
        Core::Context const& context = {});

    Response<SelectiveKeyRestoreOperation> SelectiveKeyRestoreOperationF(
        SelectiveKeyRestoreOperationOptions const& options = {},
        Core::Context const& context = {});

  private:
    std::shared_ptr<Core::Http::_internal::HttpPipeline> m_pipeline;
    Core::Url m_vaultBaseUrl;
  };
}}}} // namespace Azure::Security::KeyVault::Administration
