
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.
//
// Code generated by Microsoft (R) AutoRest C++ Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
#pragma once

#include <memory>
#include <string>
#include <vector>

#include <azure/core/context.hpp>
#include <azure/core/internal/http/pipeline.hpp>
#include <azure/core/nullable.hpp>
#include <azure/core/response.hpp>
#include <azure/core/url.hpp>
#include <azure/keyvault/administration/dll_import_export.hpp>

namespace Azure { namespace Security { namespace KeyVault { namespace Administration {
  /**
   * @brief The type specifier of the value.
   */
  class SettingTypeEnum final {
  public:
    SettingTypeEnum() = default;
    explicit SettingTypeEnum(std::string value) : m_value(std::move(value)) {}
    bool operator==(const SettingTypeEnum& other) const { return m_value == other.m_value; }
    bool operator!=(const SettingTypeEnum& other) const { return !(*this == other); }
    const std::string& ToString() const { return m_value; }
    AZURE_SECURITY_KEYVAULT_ADMINISTRATION_DLLEXPORT const static SettingTypeEnum Boolean;

  private:
    std::string m_value;
  };

  struct UpdateSettingOptions final
  {
    /**
     * The value of the pool setting.
     */
    std::string value;
  };

  struct Setting final
  {
    /**
     * The account setting to be updated.
     */
    std::string name;
    /**
     * The value of the pool setting.
     */
    std::string value;
    /**
     * The type specifier of the value.
     */
    Azure::Nullable<SettingTypeEnum> type;
  };

  /**
   * @brief The settings list result.
   */
  struct SettingsListResult final
  {
    /**
     * A response message containing a list of account settings with their
     * associated value.
     */
    std::vector<Setting> value;
  };

}}}} // namespace Azure::Security::KeyVault::Administration