parameters:
  - name: Artifacts
    type: object
    default: []
  - name: ArtifactsSource
    type: object
    default: []
  - name: ServiceDirectory
    type: string
    default: not-specified
  - name: CMakeTestOptions
    type: object
    default: []
  - name: CMakeSourceTestOptions
    type: object
    default: []

jobs:
- job: CMakeGenerate
  condition: and(succeededOrFailed(), ne(variables['Skip.CMakeGenerate'], 'true'))
  strategy:
    matrix:
      Linux:
        Pool: azsdk-pool-mms-ubuntu-1804-general
        OSVmImage: MMSUbuntu18.04
        CmakeEnvArg: ''
        AptDependencies: 'libcurl4-openssl-dev'
        VCPKG_DEFAULT_TRIPLET: 'x64-linux'
      Windows:
        Pool: azsdk-pool-mms-win-2019-general
        OSVmImage: MMS2019
        CmakeEnvArg: ''
        VCPKG_DEFAULT_TRIPLET: 'x64-windows'
      Mac:
        Pool: Azure Pipelines
        OSVmImage: macOS-10.15
        CmakeEnvArg: ''
        VCPKG_DEFAULT_TRIPLET: 'x64-osx'
  pool:
    name: $(Pool)
    vmImage: $(OSVmImage)
  variables:
    CMOCKA_XML_FILE: "%g-test-results.xml"

  steps:
  - checkout: self
    submodules: recursive

  - template: /eng/common/pipelines/templates/steps/verify-agent-os.yml
    parameters:
      AgentImage: $(OSVmImage)

  - template: /eng/common/pipelines/templates/steps/bypass-local-dns.yml

  - pwsh: sudo apt update && sudo apt install -y $(AptDependencies)
    condition: and(succeeded(), ne(variables['AptDependencies'], ''))
    displayName: Install dependencies from apt

  - template: /eng/pipelines/templates/steps/vcpkg.yml

  - script: cmake --version
    displayName: cmake --version

  - ${{ each artifact in parameters.Artifacts }}:
    - script: echo 'CMake generate tests for ${{ artifact.Name }}'
      displayName: ${{ artifact.Name }}
    - ${{ each cmakeOption in parameters.CMakeTestOptions }}:
      - template: /eng/pipelines/templates/steps/cmake-generate.yml
        parameters:
          CmakeGeneratePath: sdk/${{ parameters.ServiceDirectory }}/${{ artifact.Path }}
          GenerateArgs: ${{ cmakeOption.Value }}
          Env: "$(CmakeEnvArg)"

- job: CMakeSourceGenerate
  condition: and(succeededOrFailed(), ne(variables['Skip.CMakeGenerate'], 'true'))
  strategy:
    matrix:
      Windows:
        Pool: azsdk-pool-mms-win-2019-general
        OSVmImage: MMS2019
        CmakeEnvArg: ''
      Linux:
        Pool: azsdk-pool-mms-ubuntu-1804-general
        OSVmImage: MMSUbuntu18.04
        CmakeEnvArg: ''
        AptDependencies: 'libcurl4-openssl-dev'
      Mac:
        Pool: Azure Pipelines
        OSVmImage: macOS-10.15
        CmakeEnvArg: 'OPENSSL_ROOT_DIR=/usr/local/opt/openssl@3 OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl@3/include '
        BrewDependencies: 'openssl'

  pool:
    name: $(Pool)
    vmImage: $(OSVmImage)
  variables:
    CMOCKA_XML_FILE: "%g-test-results.xml"

  steps:
  - checkout: self
    submodules: recursive

  - template: /eng/common/pipelines/templates/steps/verify-agent-os.yml
    parameters:
      AgentImage: $(OSVmImage)

  - template: /eng/common/pipelines/templates/steps/bypass-local-dns.yml

  - pwsh: sudo apt update && sudo apt install -y $(AptDependencies)
    condition: and(succeeded(), ne(variables['AptDependencies'], ''))
    displayName: Install dependencies from apt

  - pwsh: |
      brew install $(BrewDependencies) 
    condition: and(succeeded(), ne(variables['BrewDependencies'], ''))
    displayName: Install dependencies from brew

  - script: cmake --version
    displayName: cmake --version

  - ${{ each artifact in parameters.ArtifactsSource }}:
    - script: echo 'CMake generate tests for ${{ artifact.Name }}'
      displayName: ${{ artifact.Name }}
    - ${{ each cmakeOption in parameters.CMakeSourceTestOptions }}:
      - template: /eng/pipelines/templates/steps/cmake-generate.yml
        parameters:
          CmakeGeneratePath: sdk/${{ parameters.ServiceDirectory }}/${{ artifact.Path }}
          GenerateArgs: ${{ cmakeOption.Value }}
          Env: "$(CmakeEnvArg)"