# cSpell:ignore vsts
# cSpell:ignore parseazuresdkcpp sbom

parameters:
  - name: Artifacts
    type: object
    default: []
  - name: ServiceDirectory
    type: string
    default: not-specified
  - name: TestPipeline
    type: boolean
    default: false
  - name: CoverageEnabled
    type: boolean
    default: true
  - name: CtestRegex
    type: string
    default: .*
  - name: CtestExcludeRegex
    type: string
    default: ''
  - name: BuildReleaseArtifacts
    type: boolean
    default: true
  - name: CoverageReportPath
    type: string
    default: 'sdk/*/*/*cov_xml.xml'
  - name: LineCoverageTarget
    type: number
    default: 95
  - name: BranchCoverageTarget
    type: number
    default: 70
  - name: TestEnv
    type: object
    default: []
  - name: PreTestSteps
    type: stepList
    default: []
  - name: PostTestSteps
    type: stepList
    default: []
  - name: MatrixFile
    type: string
    default: eng/pipelines/templates/stages/platform-matrix.json
  - name: JobName
    type: string
    default: Validate 
  - name: RunMetaJobs
    type: boolean
    default: true

jobs:
  - template: /eng/common/pipelines/templates/jobs/generate-job-matrix.yml
    parameters:
      GenerateJobName: ${{ parameters.JobName }}_generate_matrix
      MatrixConfigs:
        - Name: base
          Path: ${{ parameters.MatrixFile }}
          Selection: all
          GenerateVMJobs: true
      JobTemplatePath: /eng/pipelines/templates/jobs/ci.tests.yml
      OsVmImage: $(LINUXVMIMAGE)
      Pool: $(LINUXPOOL)
      AdditionalParameters:
        DisplayName: ${{ parameters.JobName }}
        Artifacts: ${{ parameters.Artifacts }}
        ServiceDirectory: ${{ parameters.ServiceDirectory }}
        TestPipeline: ${{ parameters.TestPipeline }}
        CtestRegex: ${{ parameters.CtestRegex }}
        CtestExcludeRegex: ${{ parameters.CtestExcludeRegex }}
        CoverageReportPath: ${{ parameters.CoverageReportPath }}
        CoverageEnabled: ${{ parameters.CoverageEnabled }}
        LineCoverageTarget: ${{ parameters.LineCoverageTarget }}
        BranchCoverageTarget: ${{ parameters.BranchCoverageTarget }}
        TestEnv: ${{ parameters.TestEnv }}
        PreTestSteps: ${{ parameters.PreTestSteps }}
        PostTestSteps: ${{ parameters.PostTestSteps }}

  # Disable build for cpp - client
  - ${{ if and(eq(parameters.RunMetaJobs, 'true'), ne(parameters.ServiceDirectory, 'not-specified' )) }}:
    - job:
      displayName: Create API Review
      pool:
        name: $(WINDOWSPOOL)
        image: $(WINDOWSVMIMAGE)
        os: windows
      steps:
        - task: Powershell@2
          inputs:
            filePath: $(Build.SourcesDirectory)/eng/common/scripts/Save-Package-Properties.ps1
            arguments: >
              -ServiceDirectory ${{ parameters.ServiceDirectory }}
              -OutDirectory $(Build.ArtifactStagingDirectory)/PackageInfo
            pwsh: true
            workingDirectory: $(Pipeline.Workspace)
          displayName: Dump Package properties
          condition: succeeded()

        - template: /eng/common/pipelines/templates/steps/set-default-branch.yml

        - task:  UniversalPackages@0
          displayName: Download ApiView Parser.
          inputs:
            command: download
            vstsFeed: 'internal/AzureSDKForCpp'
            vstsFeedPackage: 'parseazuresdkcpp'
            downloadDirectory: '$(System.DefaultWorkingDirectory)/parser'
            vstsPackageVersion: 0.13.0 
          condition: >-
              and(
                succeeded(),
                ne(variables['Skip.CreateApiReview'], 'true'),
                ne(variables['Build.Reason'],'PullRequest'),
                eq(variables['System.TeamProject'], 'internal')
              )

        - task: Powershell@2
          inputs:
            filePath: $(System.DefaultWorkingDirectory)/eng/scripts/Create-APIReview.ps1
            arguments: >
              -ArtifactList ('${{ convertToJson(parameters.Artifacts) }}' | ConvertFrom-Json | Select-Object Name)
              -OutPath $(Build.ArtifactStagingDirectory)
              -ApiKey "$(azuresdk-apiview-apikey)"
              -SourceBranch $(Build.SourceBranchName)
              -DefaultBranch $(DefaultBranch)
              -ParserPath $(System.DefaultWorkingDirectory)/parser/RelWithDebInfo/ParseAzureSdkCpp.exe
              -ServicePath $(Build.SourcesDirectory)/sdk/${{ parameters.ServiceDirectory }}
              -BuildId $(Build.BuildId)
              -RepoName "$(Build.Repository.Name)"
            pwsh: true
            workingDirectory: $(Pipeline.Workspace)
          displayName: Create API Review
          condition: >-
            and(
              succeeded(),
              ne(variables['Skip.CreateApiReview'], 'true'),
              ne(variables['Build.Reason'],'PullRequest'),
              eq(variables['System.TeamProject'], 'internal')
            )

    - job: GenerateReleaseArtifacts
      pool:
        name: $(WINDOWSPOOL)
        image: $(WINDOWSVMIMAGE)
        os: windows
      variables:
        VCPKG_DEFAULT_TRIPLET: 'x64-windows-static'
        Package.EnableSBOMSigning: true
      steps:
        - template: /eng/common/pipelines/templates/steps/credscan.yml
          parameters:
            SuppressionFilePath: $(Build.SourcesDirectory)/eng/CredScanSuppression.json

        - template: /eng/common/pipelines/templates/steps/check-spelling.yml
          parameters:
            ContinueOnError: false

        # Base Path Length calculated based on Visual Studio's defaults for projects.
        # By default, Visual Studio puts projects in a folder structure like this:
        # C:\Users\<username>\source\repos\<project>. That is 34 characters before project.
        # The default project name for the C++ SDK is azure-sdk-for-cpp. That is 18 additional characters (52).
        # Assuming that the user is building with the default cmake presets, cmake will create a build folder 
        # which is about 25 characters long (x64-static-debug-perftests).
        - template: /eng/common/pipelines/templates/steps/verify-path-length.yml
          parameters:
            SourceDirectory: $(Build.SourcesDirectory)
            BasePathLength: 75

        - template: /eng/common/pipelines/templates/steps/verify-links.yml
          parameters:
            ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
              Directory: ''
              Urls: (eng/common/scripts/get-markdown-files-from-changed-files.ps1)
            ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
              Directory: sdk/${{ parameters.ServiceDirectory }}
            CheckLinkGuidance: $true

        - ${{ each artifact in parameters.Artifacts }}:
          - template: /eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
            parameters:
              PackageName: ${{ artifact.Name }}
              ServiceDirectory: ${{ parameters.ServiceDirectory }}
              TestPipeline: ${{ parameters.TestPipeline }}

        - pwsh: |
            $setupFile="doxygen-1.9.7-setup.exe";

            Invoke-WebRequest `
              -MaximumRetryCount 10 `
              -Uri "https://azuresdktooling.blob.core.windows.net/dependencies/$setupFile" `
              -OutFile $setupFile `
            | Wait-Process;

            Write-Host "Installing $setupFile..."
            Start-Process -Filepath .\$setupFile -ArgumentList @("/VERYSILENT") -Wait
            Write-Host "Install complete"
            .'C:\Program Files\doxygen\bin\doxygen.exe' --version
          workingDirectory: $(Agent.TempDirectory)
          displayName: Download and Install Doxygen

        - template: /eng/pipelines/templates/steps/vcpkg.yml

        - template: /eng/pipelines/templates/steps/cmake-build.yml
          parameters:
            ServiceDirectory: ${{ parameters.ServiceDirectory }}
            Build: false
            GenerateArgs: >-
              -DINSTALL_GTEST=OFF
              -DBUILD_TESTING=OFF
              -DBUILD_TRANSPORT_CURL=OFF
              -DBUILD_DOCUMENTATION=YES

        - pwsh: npm install -g moxygen
          displayName: Install Moxygen to generate markdown for docs.microsoft.com

        # Generate package spec JSON files for tagging the repo
        - ${{ each artifact in parameters.Artifacts }}:
            - pwsh: >-
                New-Item
                -ItemType directory
                -Path $(Build.ArtifactStagingDirectory)
                -Name packages/${{ artifact.Name }}
              displayName: Create package info artifact location

            - pwsh: |
                $outputPath = Join-Path -Path $(Build.ArtifactStagingDirectory) packages/${{ artifact.Name }}/package-info.json

                $version = eng/scripts/Get-PkgVersion -ServiceDirectory ${{ parameters.ServiceDirectory }} -PackageName ${{ artifact.Path }}
                $outputObject = @{ version = $version.ToString(); name = '${{ artifact.Name }}'; packageName = "${{ artifact.Name }}_$version"; } | ConvertTo-Json

                Set-Content -Path $outputPath -Value $outputObject

                # Set AZURE_SDK_VERSION for use in Doxygen generation
                Write-Host "##vso[task.setvariable variable=AZURE_SDK_VERSION]$version"
              displayName: Create package info JSON file for ${{ artifact.Name }}

            - task: Powershell@2
              inputs:
                targetType: inline
                script: |
                  # If there is no vcpkg directory skip staging the vcpkg port artifacts
                  if (!(Test-Path build/vcpkg/ports/${{ artifact.VcpkgPortName }})) {
                    Write-Host "No vcpkg port directory at build/vcpkg/ports/${{ artifact.VcpkgPortName }}"
                    exit
                  }

                  New-Item `
                    -ItemType Directory `
                    $(Build.ArtifactStagingDirectory)/packages/${{ artifact.Name }}/vcpkg -Force

                  Copy-Item -Recurse `
                    build/vcpkg/ports/${{ artifact.VcpkgPortName }}/. `
                    $(Build.ArtifactStagingDirectory)/packages/${{ artifact.Name }}/vcpkg/port
                pwsh: true
              displayName: Copy vcpkg port files from build for ${{ artifact.Name }}

            - pwsh: |
                $outputPath = Join-Path -Path $(Build.ArtifactStagingDirectory) packages/${{ artifact.Name }}
                $changelogPath = "sdk/${{ parameters.ServiceDirectory }}/${{ artifact.Path }}/CHANGELOG.md"

                if (Test-Path $changeLogPath) {
                  Copy-Item sdk/${{ parameters.ServiceDirectory }}/${{ artifact.Path }}/CHANGELOG.md $outputPath
                } else {
                  Write-Warning "$changeLogPath does not exist"
                }
              displayName: Copy CHANGELOG.md to package artifact for ${{ artifact.Name }}

            - script: cmake --build . --target ${{ artifact.Path }}-docs
              workingDirectory: build
              displayName: Generate docs (${{ artifact.Name }}-docs)

            - template: /eng/common/pipelines/templates/steps/verify-links.yml
              parameters:
                Directory:
                Urls: annotated.html
                CheckLinkGuidance: $false
                Recursive: $true
                WorkingDirectory: build/sdk/${{ parameters.ServiceDirectory }}/${{ artifact.Path }}/docs/html

            - task: PowerShell@2
              inputs:
                targetType: filePath
                filePath: eng/scripts/New-DocsMsArtifact.ps1
                arguments: >-
                  -ServiceDirectory ${{ parameters.ServiceDirectory }}
                  -PackageName ${{ artifact.Name }}
                  -TargetFolder $(Build.ArtifactStagingDirectory)/packages/${{ artifact.Name }}/docs/docs.ms
                ignoreLASTEXITCODE: true
                pwsh: true
              displayName: Generate ${{ artifact.Name }} artifacts for docs.ms

            - task: Powershell@2
              inputs:
                filePath: $(System.DefaultWorkingDirectory)/eng/scripts/Generate-Snippets.ps1
                arguments: >
                 -source_dir $(Build.SourcesDirectory)/sdk/${{parameters.ServiceDirectory}}/${{artifact.Name}}
                 -output_dir $(Build.SourcesDirectory)/sdk/${{parameters.ServiceDirectory}}/${{artifact.Name}}
                 -verify
                pwsh: true
              displayName: Verify Snippets are correct for ${{artifact.Name}}

            - pwsh: |
                New-Item -ItemType directory -Path $(Build.ArtifactStagingDirectory) -Name docs/${{ artifact.Name }}
              displayName: Create doc artifact location

            - task: CopyFiles@2
              inputs:
                sourceFolder: $(Build.ArtifactStagingDirectory)/packages/${{ artifact.Name }}
                contents: package-info.json
                targetFolder: build/sdk/${{ parameters.ServiceDirectory }}/${{ artifact.Path }}/docs/html
              displayName: Copy package-info.json to documentation path

            - task: CopyFiles@2
              inputs:
                sourceFolder: build/sdk/${{ parameters.ServiceDirectory }}/${{ artifact.Path }}/docs/html
                targetFolder: $(Build.ArtifactStagingDirectory)/docs/${{ artifact.Name }}
              displayName: Copy documentation to artifact staging directory

            - task: Powershell@2
              inputs:
                filePath: $(Build.SourcesDirectory)/eng/common/scripts/Verify-ChangeLog.ps1
                arguments: >
                  -ChangeLogLocation sdk/${{ parameters.ServiceDirectory }}/${{ artifact.Path }}/CHANGELOG.md
                  -VersionString (Get-Content build/sdk/${{ parameters.ServiceDirectory }}/${{ artifact.Path }}/docs/html/package-info.json | ConvertFrom-Json).version
                  -ForRelease $true
                pwsh: true
              displayName: Verify CHANGELOG.md contents
              continueOnError: true
              condition: and(succeeded(), eq(variables['VerifyChangeLogForRelease'], 'true'))

        - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
          parameters:
            ArtifactPath: $(Build.ArtifactStagingDirectory)/packages
            ArtifactName: packages

        - template: /eng/common/pipelines/templates/steps/publish-1es-artifact.yml
          parameters:
            ArtifactPath: $(Build.ArtifactStagingDirectory)/docs
            ArtifactName: docs

        - template: /eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
