# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - cmake-modules/
      - eng/
      - CMakeLists.txt
      - sdk/core
      - sdk/keyvault

pr:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - cmake-modules/
      - eng/
      - CMakeLists.txt
      - sdk/core/
      - sdk/keyvault

stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: keyvault
      CtestRegex: unit-azure-security-keyvault
      LiveTestCtestRegex: azure-security-keyvault # Will also run unit test in live mode
      SubscriptionConfiguration: $(sub-config-azure-cloud-test-resources)
      Artifacts:
        - Name: azure-security-keyvault-common
          Path: azure-security-keyvault-common
        - Name: azure-security-keyvault-keys
          Path: azure-security-keyvault-keys
