#include "azure/storage/tables/dll_import_export.hpp"
#include "azure/storage/tables/models.hpp"
#include "azure/storage/tables/rest_client.hpp"
#include "azure/storage/tables/rtti.hpp"
#include "azure/storage/tables/serializers.hpp"
#include "azure/storage/tables/transactions.hpp"