# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  batch: true
  branches:
    include:
      - master
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - cmake-modules/
      - eng/
      - CMakeLists.txt
      - sdk/core

pr:
  branches:
    include:
      - master
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - cmake-modules/
      - eng/
      - CMakeLists.txt
      - sdk/core

stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: core
      # CI has static code analysis disabled, while LiveTest will have it enabled
      # In the case of changes to core we want to re-run all CI tests for all
      # libraries to check for potential regressions everywhere.
      CtestRegex: .*
      # Storage tests have no recordings
      # Identity live tests are pending to be recorded
      CtestExcludeRegex: azure-storage|azure-identity-livetest
      LiveTestCtestRegex: '"azure-core.|json-test"'
      LiveTestTimeoutInMinutes: 90 # default is 60 min. We need a little longer on worst case for Win+jsonTests
      LineCoverageTarget: 81
      BranchCoverageTarget: 43
      Artifacts:
        - Name: azure-core
          Path: azure-core
          VcpkgPortName: azure-core-cpp
