resources:
  repositories:
    - repository: azure-sdk-tools
      type: github
      name: Azure/azure-sdk-tools
      endpoint: azure

trigger:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/core
      - eng/

pr:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - sdk/core/
      - eng/

stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: core
      CtestRegex: azure-core
      Artifacts:
        - Name: azure-core
          Path: azure-core
