# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.
trigger:
  batch: true
  branches:
    include:
      - master
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - cmake-modules/
      - eng/
      - CMakeLists.txt
      - sdk/core

pr:
  branches:
    include:
      - master
      - main
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - cmake-modules/
      - eng/
      - CMakeLists.txt
      - sdk/core

stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: core
      # CI has static code analysis disabled, while LiveTest will have it enabled
      # In the case of changes to core we want to re-run all CI tests for all
      # libraries to check for potential regressions everywhere.
      CtestRegex: .*
      LiveTestCtestRegex: azure-core.|json-test
      LiveTestTimeoutInMinutes: 90 # default is 60 min. We need a little longer on worst case for Win+jsonTests
      LineCoverageTarget: 93
      BranchCoverageTarget: 55
      PreTestSteps:
        - task: UsePythonVersion@0
          displayName: 'Use Python 3.10'
          inputs:
            versionSpec: '3.10.5'
          condition: and(succeeded(), contains(variables.CmakeArgs, 'BUILD_TESTING=ON'))

        - pwsh: |
            python --version
            pip install -r requirements.txt
          workingDirectory: build/sdk/core/azure-core/test/ut
          displayName: Install Python requirements.
          condition: and(succeeded(), contains(variables.CmakeArgs, 'BUILD_TESTING=ON'))
        - pwsh: |
            Start-Process 'python.exe' `
                -ArgumentList 'sdk/core/azure-core/test/ut/websocket_server.py' `
                -NoNewWindow -PassThru -RedirectStandardOutput $(Build.SourcesDirectory)/WebSocketServer.log
          workingDirectory: build
          condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'), contains(variables.CmakeArgs, 'BUILD_TESTING=ON'))
          displayName: Launch python websocket server (Windows).

        - bash: |
            nohup python sdk/core/azure-core/test/ut/websocket_server.py > $(Build.SourcesDirectory)/WebSocketServer.log &
          workingDirectory: build
          condition: and(succeeded(), ne(variables['Agent.OS'], 'Windows_NT'), contains(variables.CmakeArgs, 'BUILD_TESTING=ON'))
          displayName: Launch python websocket server (Linux).

      PostTestSteps:
          # Shut down the test server.
        - pwsh: |
            curl.exe `
                --include `
                --no-buffer `
                --header "Connection: Upgrade" `
                --header "Upgrade: websocket" `
                --header "Host: localhost:8000" `
                --header "Origin: http://localhost:8000" `
                --header "Sec-WebSocket-Key: eaQZ9ed+LnT0zs5EvI04aQ==" `
                --header "Sec-WebSocket-Version: 13" `
                http://localhost:8000/terminateserver
          displayName: Shutdown WebSocket server.
          condition: contains(variables.CmakeArgs, 'BUILD_TESTING=ON')
        - template: /eng/common/pipelines/templates/steps/publish-artifact.yml
          parameters:
            ArtifactPath: '$(Build.SourcesDirectory)/WebSocketServer.log'
            ArtifactName: 'WebSocketLogs-$(Agent.JobName)_attempt_$(System.JobAttempt)'
            CustomCondition: contains(variables.CmakeArgs, 'BUILD_TESTING=ON')

      Artifacts:
        - Name: azure-core
          Path: azure-core
          VcpkgPortName: azure-core-cpp
        - Name: azure-core-tracing-opentelemetry
          Path: azure-core-tracing-opentelemetry
          VcpkgPortName: azure-core-tracing-opentelemetry-cpp
# Since Azure Core will run all service's tests, it requires all the expected env vars from services
      TestEnv:
# Key Vault
        - Name: AZURE_KEYVAULT_URL
          Value: "https://non-real-account.vault.azure.net"
        - Name: AZURE_KEYVAULT_HSM_URL
          Value: "https://non-real-account.managedhsm.azure.net/"
# Key Vault & Identity 
        - Name: AZURE_TENANT_ID
          Value: "33333333-3333-3333-3333-333333333333"
        - Name: AZURE_CLIENT_ID
          Value: "non-real-client"
        - Name: AZURE_CLIENT_SECRET
          Value: "non-real-secret"
# Storage
        - Name: AAD_TENANT_ID
          Value: "33333333-3333-3333-3333-333333333333"
        - Name: AAD_CLIENT_ID
          Value: "non-real-client"
        - Name: AAD_CLIENT_SECRET
          Value: "non-real-secret"
        - Name: STANDARD_STORAGE_CONNECTION_STRING
          Value: "DefaultEndpointsProtocol=https;AccountName=notReal;AccountKey=3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333;EndpointSuffix=core.windows.net"
        - Name: ADLS_GEN2_CONNECTION_STRING
          Value: "DefaultEndpointsProtocol=https;AccountName=notReal;AccountKey=3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333;EndpointSuffix=core.windows.net"
        - Name: PREMIUM_FILE_CONNECTION_STRING
          Value: "DefaultEndpointsProtocol=https;AccountName=notReal;AccountKey=3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333;EndpointSuffix=core.windows.net"
# Attestation
        - Name: LOCATION_SHORT_NAME
          Value: "wus"
        - Name: ATTESTATION_ISOLATED_URL
          Value: https://NotRealAttestationInstanceiso.wus.attest.azure.net
        - Name: ATTESTATION_AAD_URL
          Value: https://NotRealAttestationInstanceaad.wus.attest.azure.net

      CMakeTestOptions:
        - Name: Default
          Value: ''
        - Name: Test
          Value: '-DBUILD_TESTING=ON'
