trigger:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - eng/
      - CMakeLists.txt
      - sdk/core

pr:
  branches:
    include:
      - master
      - feature/*
      - release/*
      - hotfix/*
  paths:
    include:
      - eng/
      - CMakeLists.txt
      - sdk/core

stages:
  - template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
    parameters:
      ServiceDirectory: core
      CtestRegex: azure-core
      Artifacts:
        - Name: azure-core
          Path: azure-core