parameters:
  Artifacts: []
  ArtifactName: 'not-specified'

stages:
  - ${{if and(eq(variables['Build.Reason'], 'Manual'), eq(variables['System.TeamProject'], 'internal'))}}:
    - ${{ each artifact in parameters.Artifacts }}:
      - stage: Release_${{ replace(artifact.Name, '-', '_') }}
        displayName: 'Release ${{artifact.name}}'
        dependsOn: Build
        condition:  and(succeeded(), ne(variables['Build.Repository.Name'], 'Azure/azure-sdk-for-cpp'))

        jobs:
          - deployment: TagRepository
            displayName: "Create release tag"
            condition: ne(variables['Skip.TagRepository'], 'true')
            environment: github

            pool:
              name: azsdk-pool-mms-win-2019-general
              vmImage: MMS2019

            strategy:
              runOnce:
                deploy:
                  steps:
                    - checkout: self
                    - pwsh: Get-ChildItem -Recurse $(Pipeline.Workspace)/packages/${{artifact.Name}}
                      displayName: Output Visible Artifacts
                    - task: Powershell@2
                      inputs:
                        filePath: $(Build.SourcesDirectory)/eng/common/scripts/Verify-ChangeLog.ps1
                        arguments: >
                          -ChangeLogLocation $(Pipeline.Workspace)/packages/${{artifact.Name}}/CHANGELOG.md
                          -VersionString (Get-Content $(Pipeline.Workspace)/packages/${{artifact.Name}}/package-info.json | ConvertFrom-Json).version
                          -ForRelease $true
                        pwsh: true
                      displayName: Verify CHANGELOG.md contents
                    - template: /eng/common/pipelines/templates/steps/create-tags-and-git-release.yml
                      parameters:
                        ArtifactLocation: "$(Pipeline.Workspace)/packages/${{artifact.Name}}"
                        PackageRepository: CPP
                        ReleaseSha: $(Build.SourceVersion)
                        RepoId: Azure/azure-sdk-for-cpp

          - ${{if ne(artifact.skipPublishDocGithubIo, 'true')}}:
            - deployment: PublishDocs
              displayName: Publish Docs to GitHub pages
              condition: and(succeeded(), ne(variables['Skip.PublishDocs'], 'true'))
              environment: githubio
              # Release tag must exist for link substitution to work
              dependsOn: TagRepository

              pool:
                name: azsdk-pool-mms-win-2019-general
                vmImage: MMS2019

              strategy:
                runOnce:
                  deploy:
                    steps:
                      - checkout: self
                      - pwsh: Write-Host 'publish docs'
                      - pwsh: |
                          Get-ChildItem -Recurse $(Pipeline.Workspace)/docs/${{ artifact.Name }}
                        displayName: Output Visible Artifacts
                      - template: ../../../common/pipelines/templates/steps/publish-blobs.yml
                        parameters:
                          FolderForUpload: '$(Pipeline.Workspace)/docs/${{ artifact.Name }}'
                          BlobSASKey: '$(azure-sdk-docs-prod-sas)'
                          BlobName: '$(azure-sdk-docs-prod-blob-name)'
                          TargetLanguage: 'cpp'
                          ArtifactLocation: '$(Pipeline.Workspace)/packages/${{artifact.Name}}'
                          # we override the regular script path because we have cloned the build tools repo as a separate artifact.
                          ScriptPath: '$(Build.SourcesDirectory)/eng/common/scripts/copy-docs-to-blobstorage.ps1'

          - ${{ if ne(artifact.skipPublishVcpkg, 'true') }}:
            - deployment: PublishVcpkg
              displayName: Publish to vcpkg
              condition: and(succeeded(), ne(variables['Skip.PublishVcpkg'], 'true'))
              environment: github
              # This step requires the tag step
              dependsOn: TagRepository
              pool:
                name: azsdk-pool-mms-win-2019-general
                vmImage: MMS2019

              strategy:
                runOnce:
                  deploy:
                    steps:
                      - checkout: self

                      - pwsh: |
                          $branchName = "azure-sdk-for-cpp-${{ artifact.Name }}-$(Build.BuildId)"
                          if ('$(VcpkgForkBranchName)') { 
                            Write-Host "Using queue time branch name" 
                            $branchName = '$(VcpkgForkBranchName)'
                          } 
                          Write-Host "##vso[task.setvariable variable=PrBranchName]$branchName"
                        displayName: Set fork branch name

                      - pwsh: |
                          $packageSpec = Get-Content -Raw -Path "$(Pipeline.Workspace)/packages/${{artifact.Name}}/package-info.json" | ConvertFrom-Json
                          $version = $packageSpec.version
                          $title = "[${{ artifact.VcpkgPortName }}] publish version $version"

                          if ('$(VcpkgPRTitle)') { 
                            Write-Host "Using queue time PR title"
                            $title = '$(VcpkgPRTitle)'
                          }
                          Write-Host "##vso[task.setvariable variable=PrTitle]$title"
                        displayName: Set PR title

                      - pwsh: |
                          $packageSpec = Get-Content -Raw -Path "$(Pipeline.Workspace)/packages/${{artifact.Name}}/package-info.json" | ConvertFrom-Json
                          $version = $packageSpec.version
                          Write-Host "##vso[task.setvariable variable=PackageVersion]$version"
                        displayName: Set PackageVersion variable

                      - task: Powershell@2
                        inputs:
                          filePath: eng/scripts/Initialize-VcpkgRelease.ps1
                          arguments: >-
                            -GitHubRepo "$(Build.Repository.Name)"
                            -PackageSpecPath $(Pipeline.Workspace)/packages/${{artifact.Name}}/package-info.json
                            -SourceDirectory $(Pipeline.Workspace)/packages/${{artifact.Name}}/vcpkg
                            -Verbose
                          pwsh: true
                        displayName: Initialize vcpkg release

                      # There are potential race conditions if this script runs
                      # in parallel against the same branch name. Release only 
                      # one package at a time.
                      - pwsh: |
                          Write-Host "git clone https://github.com/microsoft/vcpkg $(Pipeline.Workspace)/vcpkg"
                          git clone https://github.com/microsoft/vcpkg $(Pipeline.Workspace)/vcpkg
                          if ($LASTEXITCODE -ne 0) {
                            Write-Error "Unable to check out vcpkg repo"
                            exit $LASTEXITCODE
                          }
                          
                          Write-Host "cd $(Pipeline.Workspace)/vcpkg"
                          cd $(Pipeline.Workspace)/vcpkg

                          # Clean out the folder so that template files removed
                          # are not inadvertently re-added
                          if (Test-Path "ports/${{ artifact.VcpkgPortName }}") {
                            Remove-Item -v -r "ports/${{ artifact.VcpkgPortName }}"
                          }

                          New-Item -Type Directory ports/${{ artifact.VcpkgPortName }}
                          Copy-Item -Verbose $(Pipeline.Workspace)/packages/${{artifact.Name}}/vcpkg/port/* ports/${{ artifact.VcpkgPortName }}

                          # Show artifacts copied into ports folder for PR
                          Get-ChildItem -Recurse ports/${{ artifact.VcpkgPortName }}
                          
                          Write-Host "git status"
                          git status

                          # Set the user for the scope of this particular
                          # repository
                          git config user.name "azure-sdk"
                          git config user.email "azuresdk@microsoft.com"

                          # Commit changes
                          Write-Host "git add -A"
                          git add -A 
                          Write-Host "git commit -m `"[${{ artifact.VcpkgPortName }}] Update to $(PackageVersion)`""
                          git commit -am "[${{ artifact.VcpkgPortName }}] Update to $(PackageVersion)"

                          # Run vcpkg x-add-version to add version to vcpkg file
                          Write-Host "./bootstrap-vcpkg.bat"
                          ./bootstrap-vcpkg.bat
                          Write-Host "./vcpkg.exe x-add-version ${{ artifact.VcpkgPortName }}"
                          ./vcpkg.exe x-add-version ${{ artifact.VcpkgPortName }}

                          # Amend commit to include results of x-add-version
                          Write-Host "git status"
                          git status
                          Write-Host "git add -A"
                          git add -A
                          Write-Host "git commit--amend -C (git rev-parse HEAD)"
                          git commit --amend -C (git rev-parse HEAD)

                          # Work around create-pull-request.yml logic that 
                          # checks for changes
                          Write-Host "##vso[task.setvariable variable=HasChanges]$true"
                        displayName: Commit changes for PR

                      - template: /eng/common/pipelines/templates/steps/create-pull-request.yml
                        parameters:
                          RepoOwner: Microsoft
                          RepoName: vcpkg
                          WorkingDirectory: $(Pipeline.Workspace)/vcpkg
                          PrBranchName: $(PrBranchName)
                          CommitMsg: "[${{ artifact.VcpkgPortName }}] Update to $(PackageVersion)"
                          PRTitle: $(PrTitle)
                          BaseBranchName: master
                          SkipCheckingForChanges: true

          - ${{if ne(artifact.skipUpdatePackageVersion, 'true')}}:
            - deployment: UpdatePackageVersion
              displayName: "Update Package Version"
              condition: and(succeeded(), ne(variables['Skip.UpdatePackageVersion'], 'true'))
              environment: github

              pool:
                name: azsdk-pool-mms-win-2019-general
                vmImage: MMS2019

              strategy:
                runOnce:
                  deploy:
                    steps:
                      - checkout: self
                      - pwsh: |
                          eng/scripts/Update-PkgVersion.ps1 -ServiceDirectory '${{parameters.ServiceDirectory}}' -PackageName '${{artifact.name}}'
                        displayName: Increment package version
                      - template: ../../../common/pipelines/templates/steps/create-pull-request.yml
                        parameters:
                          RepoName: azure-sdk-for-cpp
                          PRBranchName: increment-package-version-${{ parameters.ServiceDirectory }}-$(Build.BuildId)
                          CommitMsg: "Increment package version after release of ${{ artifact.name }}"
                          PRTitle: "Increment version for ${{ parameters.ServiceDirectory }} releases"