parameters:
- name: ServiceDirectory
  type: string
  default: not-specified
- name: CtestRegex
  type: string
  default: .*
- name: CtestExcludeRegex
  type: string
  default: ''
- name: CoverageEnabled
  type: boolean
  default: true
- name: LiveTestCtestRegex
  type: string
  default: ''
- name: Artifacts
  type: object
  default: []
- name: ArtifactsSource
  type: object
  default: []
- name: Location
  type: string
  default: ''
- name: SubscriptionConfiguration
  type: string
  default: $(sub-config-azure-cloud-test-resources)
- name: CoverageReportPath
  type: string
  default: 'sdk/*/*/*cov_xml.xml'
- name: LiveTestTimeoutInMinutes
  type: number
  default: 90
- name: LineCoverageTarget
  type: number
  default: 95
- name: BranchCoverageTarget
  type: number
  default: 70
- name: TestEnv
  type: object
  default: []
- name: CMakeTestOptions
  type: object
  default: []
- name: CMakeSourceTestOptions
  type: object
  default: []
  
stages:
  - stage: CMakeGeneration
    jobs:
      - template: /eng/pipelines/templates/jobs/archetype-sdk-cmake-generate.yml
        parameters:
          ServiceDirectory: ${{ parameters.ServiceDirectory }}
          Artifacts: ${{ parameters.Artifacts }}
          ArtifactsSource: ${{ parameters.ArtifactsSource }}
          CMakeTestOptions: ${{ parameters.CMakeTestOptions }}
          CMakeSourceTestOptions: ${{ parameters.CMakeSourceTestOptions }}

  - stage: Build
    dependsOn: []
    jobs:
      - template: /eng/pipelines/templates/jobs/archetype-sdk-client.yml
        parameters:
          ServiceDirectory: ${{ parameters.ServiceDirectory }}
          Artifacts: ${{ parameters.Artifacts }}
          CtestRegex: ${{ parameters.CtestRegex }}
          CtestExcludeRegex: ${{ parameters.CtestExcludeRegex }}
          CoverageEnabled: ${{ parameters.CoverageEnabled }}
          CoverageReportPath: ${{ parameters.CoverageReportPath }}
          LineCoverageTarget: ${{ parameters.LineCoverageTarget }}
          BranchCoverageTarget: ${{ parameters.BranchCoverageTarget }}
          ${{ if eq(parameters.ServiceDirectory, 'template') }}:
            TestPipeline: true
          TestEnv: ${{ parameters.TestEnv }}

  - ${{ if and(eq(variables['System.TeamProject'], 'internal'), ne(parameters.LiveTestCtestRegex, '')) }}:
    - stage: LiveTest
      dependsOn: []
      jobs:
        - template: /eng/pipelines/templates/jobs/archetype-sdk-tests.yml
          # Code coverage is enabled by default for live tests
          parameters:
            TimeoutInMinutes: ${{ parameters.LiveTestTimeoutInMinutes }}
            ServiceDirectory: ${{ parameters.ServiceDirectory }}
            CtestRegex: ${{ parameters.LiveTestCtestRegex }}
            Location: ${{ parameters.Location }}
            SubscriptionConfiguration: ${{ parameters.SubscriptionConfiguration }}
            CoverageReportPath: ${{ parameters.CoverageReportPath }}

  - ${{ if and(eq(variables['System.TeamProject'], 'internal'), not(endsWith(variables['Build.DefinitionName'], ' - tests'))) }}:
    - template: archetype-cpp-release.yml
      parameters:
        ServiceDirectory: ${{ parameters.ServiceDirectory }}
        DependsOn:
          - Build
          # Only depend on `LiveTest` if there are live tests to execute
          - ${{ if and(eq(variables['System.TeamProject'], 'internal'), ne(parameters.LiveTestCtestRegex, '')) }}:
            - LiveTest
        Artifacts: ${{ parameters.Artifacts }}
        ArtifactName: packages
        ${{ if eq(parameters.ServiceDirectory, 'template') }}:
          TestPipeline: true
