parameters:
- name: ServiceDirectory
  type: string
  default: not-specified
- name: CtestRegex
  type: string
  default: .*
- name: LiveTestCtestRegex
  type: string


stages:
  - stage: Build
    jobs:
      - template: ../jobs/archetype-sdk-client.yml
        parameters:
          ServiceDirectory: ${{ parameters.ServiceDirectory }}
          Artifacts: ${{ parameters.Artifacts }}
          CtestRegex: ${{ parameters.CtestRegex }}

  - ${{ if eq(variables['System.TeamProject'], 'internal') }}:
    - stage: LiveTest
      dependsOn: []
      jobs:
        - template: /eng/pipelines/templates/jobs/archetype-sdk-tests.yml
          parameters:
            ServiceDirectory: ${{ parameters.ServiceDirectory }}
            CtestRegex: ${{ parameters.LiveTestCtestRegex }}

  - ${{ if and(eq(variables['Build.Reason'], 'Manual'), eq(variables['System.TeamProject'], 'internal'), not(endsWith(variables['Build.DefinitionName'], ' - tests'))) }}:

    - template: archetype-cpp-release.yml
      parameters:
        ServiceDirectory: ${{parameters.ServiceDirectory}}
        DependsOn:
        - Build
        Artifacts: ${{parameters.Artifacts}}
        ArtifactName: packages
