parameters:
- name: Artifacts
  type: object
  default: []
- name: ServiceDirectory
  type: string
  default: not-specified
- name: CtestRegex
  type: string
  default: .*
- name: Coverage
  type: string
  default: 'enabled'


stages:
  - stage: Build
    jobs:
      - template: ../jobs/archetype-sdk-client.yml
        parameters:
          ServiceDirectory: ${{ parameters.ServiceDirectory }}
          Artifacts: ${{ parameters.Artifacts }}
          CtestRegex: ${{ parameters.CtestRegex }}
          Coverage: ${{ parameters.Coverage }}

  - ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal'))}}:

    - template: archetype-cpp-release.yml
      parameters:
        ServiceDirectory: ${{parameters.ServiceDirectory}}
        DependsOn:
        - Build
        Artifacts: ${{parameters.Artifacts}}
        ArtifactName: packages
