parameters:
  Artifacts: []
  ServiceDirectory: not-specified
  CtestRegex: .*


stages:
  - stage: Build
    jobs:
      - template: ../jobs/archetype-sdk-client.yml
        parameters:
          ServiceDirectory: ${{ parameters.ServiceDirectory }}
          Artifacts: ${{ parameters.Artifacts }}
          CtestRegex: ${{ parameters.CtestRegex }}

  - ${{if and(ne(variables['Build.Reason'], 'PullRequest'), eq(variables['System.TeamProject'], 'internal'))}}:

    - template: archetype-cpp-release.yml
      parameters:
        ServiceDirectory: ${{parameters.ServiceDirectory}}
        DependsOn:
        - Build
        Artifacts: ${{parameters.Artifacts}}
        ArtifactName: packages
